# Generated by Django 4.0.4 on 2023-01-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=500)),
                ('Subject', models.CharField(max_length=1000)),
                ('Message', models.TextField()),
            ],
        ),
    ]
