# Generated by Django 4.0.4 on 2023-01-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Query',
        ),
    ]
