# Generated by Django 4.0.4 on 2023-01-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='total_required',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
